FROM python:3.10

WORKDIR /Fems-Project/Backend/

COPY ./requirements.txt /Fems-Project/Backend/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /Fems-Project/Backend/requirements.txt

COPY ./main.py /Fems-Project/Backend/

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port" , "80"]